# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devdocs < Formula
  desc "DevDocs CLI — local agent runtime and management tool for the DevDocs platform"
  homepage "https://github.com/devdocsorg/multica"
  version "0.4.140"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.140/devdocs-cli-0.4.140-darwin-amd64.tar.gz"
      sha256 "307139f25924cdbdb4fdf5251dc1b2b591305217dc76b8bca8fb795cc822e299"

      define_method(:install) do
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.140/devdocs-cli-0.4.140-darwin-arm64.tar.gz"
      sha256 "d3a204bcc0a59a1ae214526b018ce24ec03f62c36f88fc1117bfde98fd02cc7d"

      define_method(:install) do
        bin.install "devdocs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.140/devdocs-cli-0.4.140-linux-amd64.tar.gz"
      sha256 "5357ea1422b0dd43672f16ab1f51e2cde4cdbcdf2778d01b7200df2f4c97d512"
      define_method(:install) do
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.140/devdocs-cli-0.4.140-linux-arm64.tar.gz"
      sha256 "14f5650ecdbd7f2eb3b3cc29312c66f3245846fee53e686cd34ced5aa29d52b2"
      define_method(:install) do
        bin.install "devdocs"
      end
    end
  end

  test do
    system "#{bin}/devdocs", "version"
  end
end
