# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devdocs < Formula
  desc "DevDocs CLI — local agent runtime and management tool for the DevDocs platform"
  homepage "https://github.com/devdocsorg/multica"
  version "0.4.111"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.111/devdocs-cli-0.4.111-darwin-amd64.tar.gz"
      sha256 "5c1ef0740e64ced70659247bdb5d9032c1b4393853c837f853ebdff05eb50e9d"

      define_method(:install) do
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.111/devdocs-cli-0.4.111-darwin-arm64.tar.gz"
      sha256 "d9cd5d0e496ae8d00e4e1c742878c6733d24e1c7fd7009e8532ef3d6a22202c2"

      define_method(:install) do
        bin.install "devdocs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.111/devdocs-cli-0.4.111-linux-amd64.tar.gz"
      sha256 "dbd2fe98b83edf298a64e073a7891428ae77d3d263ad854383893b0ea32a05a3"
      define_method(:install) do
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.111/devdocs-cli-0.4.111-linux-arm64.tar.gz"
      sha256 "55439e4b3667298336fb5eb7e609caf964897f3a93942306891a39d24976cd69"
      define_method(:install) do
        bin.install "devdocs"
      end
    end
  end

  test do
    system "#{bin}/devdocs", "version"
  end
end
