# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Compatibility formula for the renamed DevDocs CLI"
  homepage "https://github.com/devdocsorg/multica"
  version "0.4.66"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.66/multica-cli-0.4.66-darwin-amd64.tar.gz"
      sha256 "d4fce2af92c27e7978de6f82a9892cf00260e03feb3e8bac7ad38aafde4aa07f"

      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.66/multica-cli-0.4.66-darwin-arm64.tar.gz"
      sha256 "c78ef627c4a981680b18b66bbdd410cbeec2ac4cfc34f6a13866d701e23f76a2"

      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.66/multica-cli-0.4.66-linux-amd64.tar.gz"
      sha256 "190a4551e674c3b02ec00a0ad583be38bfcaf46c660a048b5e8f9078406447b2"
      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.66/multica-cli-0.4.66-linux-arm64.tar.gz"
      sha256 "ca2e8fe6c42e661e9168f323b8a80490de706af42596cd6d341593380f1633e5"
      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
    system "#{bin}/devdocs", "version"
  end
end
