# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Compatibility formula for the renamed DevDocs CLI"
  homepage "https://github.com/devdocsorg/multica"
  version "0.4.43"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.43/multica-cli-0.4.43-darwin-amd64.tar.gz"
      sha256 "8f37e1633da233c2a502992df8d45b2e23a5e49c3add0de9b19078bee17bc104"

      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.43/multica-cli-0.4.43-darwin-arm64.tar.gz"
      sha256 "6bd1466bc33dab1d32b857c68101ae2fa747eb09c928c6c40889fd65a05bcc1e"

      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.43/multica-cli-0.4.43-linux-amd64.tar.gz"
      sha256 "097116c63bb1a11ae5f756c76e5935e7e302e48f5cb8ba9df5fd2901b36bc2da"
      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.43/multica-cli-0.4.43-linux-arm64.tar.gz"
      sha256 "958e7feecd9d8546e0993d9a34b3f9397c58ef5047eb3a8187d3e66ca269d3cb"
      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
    system "#{bin}/devdocs", "version"
  end
end
