# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Compatibility formula for the renamed DevDocs CLI"
  homepage "https://github.com/devdocsorg/multica"
  version "0.4.55"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.55/multica-cli-0.4.55-darwin-amd64.tar.gz"
      sha256 "18e048864adfc11c559657dae4faedf78edfcb49caba227315937e85927ff89f"

      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.55/multica-cli-0.4.55-darwin-arm64.tar.gz"
      sha256 "1b00e19ae67c0af17e338043e68e6d81e792eeacf68298e10c6dcc6d9185f12c"

      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.55/multica-cli-0.4.55-linux-amd64.tar.gz"
      sha256 "08a9495cd44e970671774a8a6d8bddbd92644982affa80b7d0fe9379b7bffd44"
      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdocsorg/multica/releases/download/v0.4.55/multica-cli-0.4.55-linux-arm64.tar.gz"
      sha256 "da1dbeb9e39b1d0d79a571fa13d7304be4e5d320ed22a9c6be446b285a7b5cdf"
      define_method(:install) do
        bin.install "multica"
        bin.install "devdocs"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
    system "#{bin}/devdocs", "version"
  end
end
